### ISSUE TITLE
incorrect version

### ISSUE THREAD

**Issue by bbodenmiller** [sonatype/nxrm3-ha-repository#23]
https://github.com/sonatype/nxrm3-ha-repository/blob/main/nxrm-aws-ha-helm/Chart.yaml reports `3.61.0` but https://github.com/sonatype/nxrm3-ha-repository/blob/main/nxrm-aws-ha-helm/values.yaml is coded to `3.58.1`. Old chart https://github.com/sonatype/nxrm3-helm-repository/tree/main/nexus-repository-manager does not have this issue making it impossible to upgrade to HA chart.

**Comment by vswaminathan777** [comment]
Please use our latest Helm Charts https://github.com/sonatype/nxrm3-ha-repository. The  Nexus Repository version is configurable and has 'latest' as the  as the default value for version in values.yaml
