### ISSUE TITLE
Helm Upgrade issue

### ISSUE THREAD

**Issue by bonickle** [sonatype/nxrm3-ha-repository#31]
It it seems it is not possible to bump  the chart version and upgrade the deployment in place.

Since the ingress, statefulset, storageclass and secret-class names are pined with the chart version, when you go to update the helm chart, it fails trying to create the new ingress since the old ingress still exists whit the path name being used. 

I recommend not  pinning the chart version in resource names to avoid conflicts when create resources and duplicating other resources.  It seems like the only way to update the chart right now is to uninstall the old version to reinstall the new version.

```
Error: UPGRADE FAILED:. original upgrade error: failed to create resource: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "nexus.stg.bsf.tools" and path "/" is already defined in ingress nexus/nxrm-ha-aws-59.0.0.nexus-ingress: no StorageClass with the name "nxrm-ha-aws-59.0.0-nexus-ebs-storage" found
```

**Comment by vswaminathan777** [comment]
@bonickle We have addressed this in the latest Helm Charts that we have published - https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-ha
