### ISSUE TITLE
AWS RDS Connection Bug

### ISSUE THREAD

**Issue by bonickle** [sonatype/nxrm3-ha-repository#48]
Not sure if this is a bug with the chart, probably with the actual Nexus software/image.

On a helm deploy/upgrade the first pod always seems to fail to connect to the DB with the error "dataset Nexus not found", when it is bounced and recreated it connects fine without any issues.

**Comment by vswaminathan777** [comment]
@bonickle we were unable to reproduce this issue at our end. If you are still facing this issue, please reach out to our support team for further assistance.
