### ISSUE TITLE
Assigned Identity in the secret provider class is hard-coded

### ISSUE THREAD

**Issue by hadams95** [sonatype/nxrm3-ha-repository#7]
https://github.com/sonatype/nxrm3-ha-repository/blob/2a3a7cb492d7f607acbd68ac580d4251cd5daec8/nxrm-azure-ha-helm/templates/secret.yaml#L26

As seen at the link above, this variable is not populated by the chart values.  In order to utilize the chart, I cloned it locally and edited the template file accordingly with the managed identity assigned to my cluster

**Comment by bobotimi** [comment]
Thank you for your contribution @hadams95 . We have reviewed and merged your PR.
