### ISSUE TITLE
NXRM High Availability (HA) POD Startup Error

### ISSUE THREAD

**Issue by abhijitvk** [sonatype/nxrm3-ha-repository#83]
Our team is evaluating Nexus Pro HA for our AWS Kubernetes environment. 

We are following the Helm Chart and documentation as available on: https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-ha 
 
In our setup, we are using PostgreSQL external database and would use S3 BLOBSTORE. The POD starts up fine with the Replica count of 1 for the StatefulSet. However, as soon as we try and scale up for the second instance, that one fails with the error “**Back-off restarting failed container nxrm-app in pod nxrm-statefulset-nexus-1_namespace(20092921-0bab-48ca-95d0-e7b26ac4bd6b)**”
 
We are looking for assistance to determine what configuration we might need to enable cluster for Nexus so that the second instance comes up fine. POD logs and events don’t provide any further details as this seems to be some app start-up issue causing the CRASHLOOP (see attached logs for success and failure)
 
Note that we have an Nexus Enterprise PRO license

**Comment by vswaminathan777** [comment]
@abhijitvk apologize for the late response. If this is still an open issue, please raise a support ticket so that we can assist you with it.
