### ISSUE TITLE
Read Me link needs to be updated

### ISSUE THREAD

**Issue by david-low** [sonatype/nxrm3-ha-repository#9]
ReadMe has this link which is no longer valid. Takes me to a 404 
[Helm chart for those deploying to an AWS environment](https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-aws-resiliency).

I believe it should now point to:
https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-aws-ha-helm

**Comment by bobotimi** [comment]
> ReadMe has this link which is no longer valid. Takes me to a 404 [Helm chart for those deploying to an AWS environment](https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-aws-resiliency).
> 
> I believe it should now point to: https://github.com/sonatype/nxrm3-ha-repository/tree/main/nxrm-aws-ha-helm

@david-low Thank you. We'll update this.

**Comment by bobotimi** [comment]
@david-low This issue has now been resolved. Thank you.
